### ISSUE TITLE
"Invalid Entries" in 1.19.2 Modpack

### ISSUE THREAD

**Issue by Hmloughin** [Aureljz/WhenDungeonsArise--Fabric#13]
I think this is one of my favourite mods ever so I really hope this can be resolved. I've included the latest log. I've tried using all versions in the modpack in case something was incompatible with an update, but no dice. 
[latest.log](https://github.com/Aureljz/WhenDungeonsArise--Fabric/files/11357979/latest.log)

**Comment by Aureljz** [comment]
I don't think this issue is caused by WDA. There's a warn about 'credits' entry, but no errors.
The actual crash seems to point here:

```
at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23) ~[Patchouli-1.19.2-77-FABRIC.jar:?]
```
